spring:
  config: 
    import: optional:secrets.yml

  datasource:
    url: jdbc:mysql://localhost:3306/algalog?createDatabaseIfNotExist=true&serverTimeZone=UTC
  jpa:
    show-sql: true
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
